apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}-{{ .Values.ingname }}
spec:
    ingressClassName: nginx
    rules:
      - host: {{.Values.hostname }}
        http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: {{ .Release.Name }}-{{ .Values.nextService.name }}
                  port:
                    number: {{ .Values.nextService.port }}
              path: /