apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgreName }}-deployment
  labels:
    app: {{ .Values.postgreLabels.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.postgreLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgreLabels.app }}
    spec:
      containers:
      - name: {{ .Values.postgreName }}-container
        image: {{ .Values.postgresSpec.image }}:{{.Values.postgresSpec.tag }}
        ports:
        - containerPort: {{ .Values.postgresSpec.contport }}
        env:
          - name: {{ .Values.data.user }}
            valueFrom:  
              configMapKeyRef:
               name: {{ .Values.configname }}
               key: user
          - name: {{ .Values.data.postPass }}
            value: medo
            # valueFrom:  
            #   secretKeyRef:
            #     name: {{ .Values.secretName }}
            #     key: pass
          - name: {{ .Values.data.postdb }}
            valueFrom:  
              configMapKeyRef:
               name: {{ .Values.configname }}
               key: db
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postService.name }}
spec:
  selector:
    app: {{ .Values.postgreLabels.app }}
  ports:
  - port: {{ .Values.postService.port }}
    targetPort: {{ .Values.postgresSpec.contport }}
