apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgreName }}-pv-claim
  labels:
    app: {{ .Values.postgreLabels.app }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
