apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pv-claim
  labels:
    {{- include "postlabels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: {{ .Values.storage.size }}
