apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
type: Opaque
data:
  # user: bXlzcWw=
  {{- with .Values.secretData }}

  user: {{ .user | b64enc | quote }}
  password: {{ .password | b64enc | quote }}
  root: {{ .root | b64enc | quote }}
  pass: {{ .pass | b64enc | quote }}
  {{- end -}}
