apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-svc
spec:
  selector:
    {{- include "postlabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.tport }}
