apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nextcloud-svc
spec:
  type: {{ .Values.service.type }}
  selector:
     {{- include "labels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.tport }}