apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-svc	
spec:
  selector:
    {{- include "redislabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.tport }}