apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:  
              configMapKeyRef:
               name: app-configmap
               key: user
          - name: POSTGRES_PASSWORD
            value: medo
            # valueFrom:  
            #   secretKeyRef:
            #     name: app-secret
            #     key: pass
          - name: POSTGRES_DB
            valueFrom:  
              configMapKeyRef:
               name: app-configmap
               key: db
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
